spring:
  datasource:
    url: jdbc:h2:mem:springexample;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8081
  undertow:
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
#
#spring:
#  jersey:
#    application-path: /
#logging:
#  level: trace

token:
  signature: 123456